# Generated by Django 3.2 on 2021-04-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
